import {useEffect,useState} from 'react'
import {useNavigate} from '@tanstack/react-router'
import {useServerFn} from '@tanstack/react-start'
import {ShieldAlert,ArrowLeft,RefreshCw} from 'lucide-react'
import {toast} from 'sonner'
import AppLayout from '@/components/AppLayout'
import {useAuth} from '@/contexts/AuthContext'
import {Button} from '@/components/ui/button'
import {createClient} from '@/lib/supabase/client'
import {moderateVibz,vibzMediaUrl} from '@/lib/vibz.functions'
import {appConfirm} from '@/components/ui/AppDialog'

const reasons=['Nudity Content','Sexual Content','Soft Porn Content','CSAM Content','Unfit Content'] as const
type Item={id:string;creator_id:string;created_at:string;media_path:string;caption:string;status:string;categories:string[];confidence:number|null;review_notes:string|null;user_profiles?:{full_name:string;username:string|null}|null}
function ReviewItem({item,done}:{item:Item;done:()=>void}){
 const signed=useServerFn(vibzMediaUrl);const decide=useServerFn(moderateVibz);const [url,setUrl]=useState('');const [reason,setReason]=useState<(typeof reasons)[number]|''>('');const [busy,setBusy]=useState(false);const [history,setHistory]=useState<{id:string;action:string;categories:string[];details:string|null;created_at:string;email_status:string|null}[]>([])
 useEffect(()=>{signed({data:{postId:item.id}}).then(setUrl).catch(()=>{});createClient().from('vibz_moderation').select('id,action,categories,details,created_at,email_status').eq('post_id',item.id).order('created_at',{ascending:false}).then(({data})=>setHistory(data??[]))},[item.id,signed])
 const act=async(action:'keep'|'delete'|'quarantine')=>{if(action==='delete'&&!reason){toast.error('Select a deletion reason');return}if(action==='delete'&&!await appConfirm({title:'Remove this VibZ?',message:`Reason: ${reason}. This will hide the video and email its creator.`,confirmLabel:'Delete VibZ'}))return;setBusy(true);try{await decide({data:{postId:item.id,action,reason:reason||undefined}});toast.success('Decision recorded');done()}catch(e){toast.error(e instanceof Error?e.message:'Review failed')}finally{setBusy(false)}}
 return <article className="border border-border rounded-xl p-4 space-y-3 bg-card"><div className="flex justify-between gap-2 text-sm"><div><strong>{item.user_profiles?.full_name||'Creator'}</strong> {item.user_profiles?.username&&`@${item.user_profiles.username}`}<p className="text-muted-foreground text-xs break-all">ID: {item.creator_id}</p></div><span className="text-muted-foreground">{new Date(item.created_at).toLocaleString()}</span></div>{url?<video controls playsInline src={url} className="w-full max-h-72 bg-foreground/10 rounded-lg"/>:<p className="text-sm">Preview unavailable</p>}<p className="text-sm">{item.caption}</p><div className="text-xs space-y-1"><p>Status: {item.status} · AI confidence: {item.confidence===null?'Unavailable':`${Math.round(item.confidence*100)}%`}</p><p>Detected: {item.categories.join(', ')||'Uncertain / review needed'}</p><p>{item.review_notes}</p></div><details className="text-xs"><summary>Previous moderation actions ({history.length})</summary><div className="space-y-2 mt-2">{history.map(h=><p key={h.id}>{new Date(h.created_at).toLocaleString()} · {h.action} · {h.categories.join(', ')} {h.details} {h.email_status&&`· Email: ${h.email_status}`}</p>)}</div></details>{item.status!=='deleted'&&<div className="flex flex-wrap gap-2 items-center"><Button size="sm" disabled={busy} onClick={()=>act('keep')}>Keep VibZ</Button>{item.status==='published'&&<Button variant="outline" size="sm" disabled={busy} onClick={()=>act('quarantine')}>Quarantine</Button>}<select aria-label="Deletion reason" value={reason} onChange={e=>setReason(e.target.value as typeof reason)} className="bg-input text-foreground border border-border rounded-md p-2 text-sm"><option value="">Select reason</option>{reasons.map(r=><option key={r}>{r}</option>)}</select><Button size="sm" variant="destructive" disabled={busy||!reason} onClick={()=>act('delete')}>Delete VibZ</Button></div>}</article>
}
export default function AlteredVibzPage(){const {user,profile,loading,isAdmin}=useAuth();const navigate=useNavigate();const [items,setItems]=useState<Item[]>([]);const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [tab,setTab]=useState<'review'|'history'>('review');const reload=async()=>{setBusy(true);const {data,error:e}=await createClient().from('vibz_posts').select('id,creator_id,created_at,media_path,caption,status,categories,confidence,review_notes,user_profiles!vibz_posts_creator_id_fkey(full_name,username)').in('status',tab==='review'?['flagged','quarantined','pending']:['deleted','published']).order('created_at',{ascending:false}).limit(100);if(e)setError(e.message);else{setItems(data as Item[]??[]);setError('')}setBusy(false)};useEffect(()=>{if(profile&&isAdmin?.())reload()},[profile?.id,tab]);useEffect(()=>{if(!loading&&profile&&!isAdmin?.())navigate({to:'/admin'})},[loading,profile]);return <AppLayout><main className="max-w-4xl mx-auto px-4 py-6 pb-28 space-y-5"><div className="flex items-center gap-2"><Button variant="ghost" size="icon" onClick={()=>navigate({to:'/admin'})} aria-label="Back to admin"><ArrowLeft/></Button><ShieldAlert className="text-primary"/><h1 className="font-bold text-xl flex-1">Altered VibZ</h1><Button variant="ghost" size="icon" aria-label="Refresh" onClick={reload}><RefreshCw/></Button></div><div className="flex gap-2"><Button variant={tab==='review'?'default':'outline'} onClick={()=>setTab('review')}>Needs review</Button><Button variant={tab==='history'?'default':'outline'} onClick={()=>setTab('history')}>Decision history</Button></div>{busy?<p>Loading reviews…</p>:error?<p role="alert">{error}</p>:items.length?items.map(i=><ReviewItem key={i.id} item={i} done={reload}/>):<p className="text-muted-foreground">{tab==='review'?'No VibZ waiting for review.':'No decisions yet.'}</p>}</main></AppLayout>}
