import { useCallback, useEffect, useRef, useState } from 'react'
import { Link } from '@tanstack/react-router'
import { useServerFn } from '@tanstack/react-start'
import { Clapperboard, Plus, Search, Heart, MessageCircle, Share2, X, ArrowLeft, Upload, Video, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '@/contexts/AuthContext'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { getVibzFeed, getVibzProfile, searchVibzPeople, vibzMediaUrl, createVibz } from '@/lib/vibz.functions'
import { reviewVibzUpload } from '@/lib/vibz-review.functions'
import { appConfirm } from '@/components/ui/AppDialog'

const policy = 'VibTribe does not tolerate or promote nudity, sexual content, pornography/soft-pornographic content, CSAM, or other content that violates our Community Guidelines.'
type Post = { id:string;creator_id:string;media_path:string;caption:string;created_at:string;likes_count:number;comments_count:number;shares_count:number;creator_name?:string|null;creator_username?:string|null;creator_avatar?:string|null;creator_bio?:string|null;vibed_in?:boolean;liked?:boolean;status?:string }
type Person = {id:string;full_name:string;username:string|null;avatar_url:string|null;bio:string|null;vibemates:number;vibein_count?:number;total_likes?:number;total_comments?:number;total_shares?:number;vibed_in:boolean}
const compact = (n:number) => Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n)
const client = createClient()

function VideoCard({post,onCreator,onUpdate}:{post:Post;onCreator:(id:string)=>void;onUpdate:()=>void}) {
  const {user} = useAuth()
  const getUrl = useServerFn(vibzMediaUrl)
  const [url,setUrl] = useState('')
  const [error,setError] = useState('')
  const [comments,setComments] = useState(false)
  const [list,setList] = useState<{id:string;body:string;user_id:string}[]>([])
  const [body,setBody] = useState('')
  const [busy,setBusy] = useState(false)
  const [liked,setLiked] = useState(!!post.liked)
  const [vibed,setVibed] = useState(!!post.vibed_in)
  const [likes,setLikes] = useState(post.likes_count)
  const [commentCount,setCommentCount] = useState(post.comments_count)
  const [shareCount,setShareCount] = useState(post.shares_count)
  const video = useRef<HTMLVideoElement>(null)
  const wrapper = useRef<HTMLDivElement>(null)
  useEffect(()=>{let live=true;getUrl({data:{postId:post.id}}).then(u=>{if(live)setUrl(u)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[post.id,getUrl])
  useEffect(()=>{const target=wrapper.current;if(!target)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)video.current?.play().catch(()=>{});else video.current?.pause()},{threshold:.6});observer.observe(target);return()=>observer.disconnect()},[url])
  const toggleLike=async()=>{if(!user||busy)return;setBusy(true);const next=!liked;const {error:e}=next?await client.from('vibz_likes').insert({post_id:post.id,user_id:user.id}):await client.from('vibz_likes').delete().eq('post_id',post.id).eq('user_id',user.id);if(e)toast.error(e.message);else {setLiked(next);setLikes(n=>n+(next?1:-1))}setBusy(false)}
  const toggleVibe=async()=>{if(!user||busy)return;setBusy(true);const next=!vibed;const {error:e}=next?await client.from('vibein').insert({creator_id:post.creator_id,follower_id:user.id}):await client.from('vibein').delete().eq('creator_id',post.creator_id).eq('follower_id',user.id);if(e)toast.error(e.message);else setVibed(next);setBusy(false)}
  const loadComments=async()=>{const {data,error:e}=await client.from('vibz_comments').select('id,body,user_id').eq('post_id',post.id).order('created_at',{ascending:false}).limit(60);if(e)toast.error(e.message);else setList(data??[]);setComments(true)}
  const sendComment=async()=>{if(!user||busy||!body.trim())return;setBusy(true);const {error:e}=await client.from('vibz_comments').insert({post_id:post.id,user_id:user.id,body:body.trim()});if(e)toast.error(e.message);else{setBody('');setCommentCount(n=>n+1);await loadComments()}setBusy(false)}
  const share=async()=>{if(!user)return;try {const link=`${location.origin}/vibz?post=${post.id}`;if(navigator.share)await navigator.share({title:'VibZ on VibTribe',url:link});else{await navigator.clipboard.writeText(link);toast.success('Link copied')}const {error:e}=await client.from('vibz_shares').insert({post_id:post.id,user_id:user.id});if(!e)setShareCount(n=>n+1)}catch{/* share cancelled */}}
  const remove=async()=>{if(!await appConfirm({title:'Delete VibZ?',message:'Your video and its engagement will be removed.',confirmLabel:'Delete'}))return;const {error:e}=await client.from('vibz_posts').delete().eq('id',post.id);if(e)toast.error(e.message);else{await client.storage.from('vibz-media').remove([post.media_path]);onUpdate()}}
  return <section ref={wrapper} className="relative w-full h-[min(72dvh,740px)] min-h-[430px] bg-foreground/10 border border-border rounded-xl overflow-hidden snap-start snap-always flex items-center justify-center">
    {url?<video ref={video} src={url} playsInline loop controls preload="metadata" className="w-full h-full object-contain bg-foreground/10"/>:<div className="text-muted-foreground text-sm">{error||'Loading video…'}</div>}
    <div className="absolute bottom-14 left-3 right-16 pointer-events-none text-foreground bg-background/80 backdrop-blur-sm rounded-lg p-3 max-w-md">
      <button onClick={()=>onCreator(post.creator_id)} className="pointer-events-auto font-semibold text-left">{post.creator_name||'VibTribe creator'} {post.creator_username&&<span className="text-primary">@{post.creator_username}</span>}</button>
      {post.caption&&<p className="text-sm mt-1 break-words">{post.caption}</p>}
      {post.status && post.status !== 'published' && <p className="text-xs text-muted-foreground mt-1">{post.status === 'pending' ? 'Safety review in progress — visible only to you' : `${post.status} — not visible to others`}</p>}
    </div>
    <div className="absolute right-2 bottom-14 flex flex-col items-center gap-2 p-1 bg-background/80 backdrop-blur rounded-xl">
      {post.creator_id !== user?.id && <Button variant="ghost" size="sm" onClick={toggleVibe} disabled={busy} aria-label={vibed?'Remove VibeIn':'VibeIn'}>{vibed?'VibeIn’d':'VibeIn'}</Button>}
      <Button variant="ghost" size="icon" aria-label="Like VibZ" onClick={toggleLike} disabled={busy||post.status!=='published'&&!!post.status}><Heart className={liked?'fill-primary text-primary':''}/></Button><span className="text-xs">{compact(likes)}</span>
      <Button variant="ghost" size="icon" aria-label="Comments" onClick={loadComments} disabled={post.status!=='published'&&!!post.status}><MessageCircle/></Button><span className="text-xs">{compact(commentCount)}</span>
      <Button variant="ghost" size="icon" aria-label="Share VibZ" onClick={share} disabled={post.status!=='published'&&!!post.status}><Share2/></Button><span className="text-xs">{compact(shareCount)}</span>
      {user?.id===post.creator_id && post.status!=='quarantined'&&<Button variant="ghost" size="icon" aria-label="Delete your VibZ" onClick={remove}><Trash2/></Button>}
    </div>
    {comments&&<div className="absolute inset-x-0 bottom-0 max-h-[65%] bg-background border-t border-border rounded-t-xl flex flex-col p-3 shadow-xl"><div className="flex items-center justify-between"><h3 className="font-semibold">Comments</h3><Button size="icon" variant="ghost" onClick={()=>setComments(false)} aria-label="Close comments"><X/></Button></div><div className="flex-1 overflow-y-auto space-y-3 py-3">{list.length?list.map(c=><p key={c.id} className="text-sm break-words">{c.body} {c.user_id===user?.id&&<Button size="sm" variant="ghost" onClick={async()=>{const {error:e}=await client.from('vibz_comments').delete().eq('id',c.id);if(e)toast.error(e.message);else{setCommentCount(n=>n-1);loadComments()}}}>Delete</Button>}</p>):<p className="text-sm text-muted-foreground">Start the conversation.</p>}</div><form onSubmit={e=>{e.preventDefault();sendComment()}} className="flex gap-2"><input value={body} onChange={e=>setBody(e.target.value)} maxLength={500} placeholder="Add a comment…" className="min-w-0 flex-1 bg-input border border-border rounded-md px-3 text-foreground"/><Button disabled={busy||!body.trim()}>Post</Button></form></div>}
  </section>
}

async function inspectVideo(file:File):Promise<{duration:number;frames:string[]}> {
  const url=URL.createObjectURL(file)
  const video=document.createElement('video');video.preload='auto';video.muted=true;video.playsInline=true;video.src=url
  const wait=(event:string)=>new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Unable to inspect video. Try a supported MP4.')),15000);video.addEventListener(event,()=>{clearTimeout(timer);resolve()},{once:true});video.addEventListener('error',()=>{clearTimeout(timer);reject(new Error('Unable to read this video.'))},{once:true})})
  try {await wait('loadedmetadata');const duration=video.duration;if(!Number.isFinite(duration)||duration<=0||duration>=120)throw new Error('VibZ must be shorter than 2 minutes. Please trim this video and try again.');const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const context=canvas.getContext('2d');if(!context)throw new Error('Could not inspect this video');const frames:string[]=[];for(const fraction of [.04,.2,.4,.6,.8,.96]){video.currentTime=Math.max(0,Math.min(duration-0.05,duration*fraction));await wait('seeked');context.drawImage(video,0,0,320,180);frames.push(canvas.toDataURL('image/jpeg',.58))}return {duration,frames}}finally{URL.revokeObjectURL(url);video.removeAttribute('src');video.load()}
}

export default function VibzExperience({profileId}:{profileId?:string}) {
  const {user,loading,isAdmin}=useAuth()
  if(loading)return <p className="p-8 text-center text-muted-foreground">Loading…</p>
  if(!user)return <p className="p-8 text-center">Sign in to watch VibZ.</p>
  if(!isAdmin?.())return <div className="p-8 text-center"><p className="text-muted-foreground">VibZ is currently available to admins only.</p><Button asChild variant="outline" className="mt-4"><Link to="/">Back to Chats</Link></Button></div>
  return <AdminVibzExperience profileId={profileId}/>
}

function AdminVibzExperience({profileId}:{profileId?:string}) {
  const {user}=useAuth();const feedFn=useServerFn(getVibzFeed);const profileFn=useServerFn(getVibzProfile);const searchFn=useServerFn(searchVibzPeople);const createFn=useServerFn(createVibz);const reviewFn=useServerFn(reviewVibzUpload)
  const [posts,setPosts]=useState<Post[]>([]);const [person,setPerson]=useState<Person|null>(null);const [selected,setSelected]=useState<string|null>(profileId??null);const [mode,setMode]=useState<'feed'|'search'|'create'>(profileId?'feed':'feed');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [results,setResults]=useState<Person[]>([]);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const [caption,setCaption]=useState('');const [duration,setDuration]=useState(0);const [frames,setFrames]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [uploadProgress,setUploadProgress]=useState(0);const [chooseOpen,setChooseOpen]=useState(false);const input=useRef<HTMLInputElement>(null)
  const refresh=useCallback(async()=>{setLoading(true);setError('');try{const list=await feedFn({data:{creatorId:selected??undefined}});setPosts(list as Post[]);if(selected)setPerson(await profileFn({data:{id:selected}}) as Person|null);else setPerson(null)}catch(e){setError(e instanceof Error?e.message:'Could not load VibZ')}finally{setLoading(false)}},[selected,feedFn,profileFn])
  useEffect(()=>{refresh()},[refresh])
  useEffect(()=>{if(query.trim().length<2){setResults([]);return}const timer=setTimeout(()=>searchFn({data:{query}}).then(r=>setResults(r as Person[])).catch(e=>toast.error(e.message)),300);return()=>clearTimeout(timer)},[query,searchFn])
  const selectFile=async(f?:File)=>{if(!f)return;setError('');if(f.size>50*1024*1024){setError('Maximum video size is 50 MB.');return}if(f.type!=='video/mp4'){setError('Please use an MP4 video for reliable playback.');return}setBusy(true);try{const details=await inspectVideo(f);if(preview)URL.revokeObjectURL(preview);setFile(f);setDuration(details.duration);setFrames(details.frames);setPreview(URL.createObjectURL(f));setChooseOpen(false)}catch(e){setError(e instanceof Error?e.message:'Could not inspect video')}finally{setBusy(false)}}
  const cancel=()=>{if(preview)URL.revokeObjectURL(preview);setFile(null);setPreview('');setFrames([]);setCaption('');setMode('feed');setError('')}
  const publish=async()=>{if(!file||!user||busy)return;setBusy(true);setError('');setUploadProgress(1);const path=`${user.id}/${crypto.randomUUID()}.mp4`;try{
    // Supabase's upload API reports completion, not intermediate byte progress.
    const {error:uploadError}=await client.storage.from('vibz-media').upload(path,file,{contentType:'video/mp4',upsert:false});if(uploadError)throw uploadError;setUploadProgress(70)
    const id=await createFn({data:{mediaPath:path,duration,caption:caption.trim()}});if(!id)throw new Error('Unable to create VibZ');setUploadProgress(85)
    const result=await reviewFn({data:{postId:id,frames}});setUploadProgress(100);toast.success(result.status==='published'?'Your VibZ is live!':'Your VibZ is private while our safety team reviews it.');cancel();setSelected(user.id);refresh()
  }catch(e){setError(e instanceof Error?e.message:'Upload failed. Retry when connected.');await client.storage.from('vibz-media').remove([path])}finally{setBusy(false);setUploadProgress(0)}}
  if(!user)return <p className="p-8 text-center">Sign in to watch VibZ.</p>
  return <div className="max-w-3xl mx-auto px-3 sm:px-5 py-3 pb-28 text-foreground">
    <div className="flex items-center gap-2 mb-3"><Button variant="ghost" size="icon" aria-label="Back to VibZ" onClick={()=>{setMode('feed');setSelected(null);cancel()}}><Clapperboard/></Button><h1 className="font-bold text-xl flex-1">{mode==='search'?'Discover people':mode==='create'?'Create VibZ':selected?'Creator profile':'VibZ'}</h1>{mode==='feed'&&!selected&&<><Button variant="ghost" size="icon" aria-label="Create VibZ" onClick={()=>setChooseOpen(true)}><Plus/></Button><Button variant="ghost" size="icon" aria-label="Search creators" onClick={()=>setMode('search')}><Search/></Button></>}{(selected||mode==='search'||mode==='create')&&<Button variant="ghost" size="icon" aria-label="Back" onClick={()=>{setSelected(null);cancel()}}><ArrowLeft/></Button>}</div>
    {error&&<div role="alert" className="p-3 mb-3 rounded-lg border border-destructive text-destructive text-sm">{error} {mode==='feed'&&<Button variant="ghost" onClick={refresh}>Retry</Button>}</div>}
    {chooseOpen&&<div className="fixed inset-0 z-50 bg-background/90 flex items-center justify-center p-4"><div className="bg-card border border-border rounded-xl p-5 w-full max-w-sm space-y-3"><div className="flex justify-between"><h2 className="font-semibold">Create VibZ</h2><Button variant="ghost" size="icon" onClick={()=>setChooseOpen(false)} aria-label="Close"><X/></Button></div><Button className="w-full" onClick={()=>{setMode('create');setChooseOpen(false);input.current?.click()}}><Upload/>Upload from device</Button><Button variant="outline" className="w-full" onClick={()=>{setMode('create');setChooseOpen(false);input.current?.click()}}><Video/>Record video (if supported)</Button></div></div>}
    <input ref={input} type="file" accept="video/mp4" className="hidden" aria-label="Choose MP4 video" onChange={e=>{selectFile(e.target.files?.[0]);e.target.value=''}}/>
    {mode==='create'&&<div className="space-y-4"><p className="text-sm text-muted-foreground">Videos must be shorter than 2 minutes and no larger than 50 MB.</p>{preview?<video src={preview} controls playsInline className="w-full max-h-[50dvh] rounded-xl bg-foreground/10"/>:<Button variant="outline" onClick={()=>input.current?.click()}>Choose MP4 video</Button>}{duration>0&&<p className="text-sm">Duration: {Math.round(duration)}s</p>}<label className="block text-sm">Caption (optional)<textarea className="mt-1 w-full rounded-md bg-input border border-border p-3 text-foreground" maxLength={500} rows={3} value={caption} onChange={e=>setCaption(e.target.value)}/></label><p className="text-sm">Your VibZ will be visible to other signed-in VibTribe members after safety review. It is not end-to-end encrypted.</p><p className="text-xs text-muted-foreground">{policy}</p>{busy&&<progress className="w-full accent-primary" value={uploadProgress||undefined} max={100} aria-label="Upload progress"/>}<div className="flex gap-2"><Button onClick={publish} disabled={!file||busy}>{busy?'Publishing…':'Publish VibZ'}</Button><Button variant="outline" disabled={busy} onClick={cancel}>Cancel</Button></div></div>}
    {mode==='search'&&<><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search username or display name" aria-label="Search creators" className="w-full bg-input border border-border rounded-lg p-3 mb-4 text-foreground"/>{query.length<2?<p className="text-muted-foreground text-sm">Type at least 2 characters.</p>:results.length===0?<p className="text-muted-foreground text-sm">No creators found.</p>:<div className="space-y-2">{results.map(p=><div key={p.id} className="flex items-center justify-between gap-2 border-b border-border py-3"><Button variant="ghost" className="min-w-0 h-auto text-left flex-col items-start" onClick={()=>{setSelected(p.id);setMode('feed')}}><span className="truncate max-w-full font-semibold">{p.full_name}</span><span className="text-xs text-muted-foreground">@{p.username||'member'} · {compact(Number(p.vibemates))} VibeMates</span></Button><Button variant="outline" size="sm" onClick={async()=>{const {error:e}=p.vibed_in?await client.from('vibein').delete().eq('creator_id',p.id).eq('follower_id',user.id):await client.from('vibein').insert({creator_id:p.id,follower_id:user.id});if(e)toast.error(e.message);else setResults(old=>old.map(r=>r.id===p.id?{...r,vibed_in:!r.vibed_in,vibemates:Number(r.vibemates)+(r.vibed_in?-1:1)}:r))}}>{p.vibed_in?'VibeIn’d':'VibeIn'}</Button></div>)}</div>}</>}
    {mode==='feed'&&<>{person&&<div className="py-4 border-b border-border mb-4"><h2 className="text-xl font-bold">{person.full_name}</h2><p className="text-primary">@{person.username||'member'}</p><p className="text-sm my-2">{person.bio}</p><div className="flex flex-wrap gap-4 text-sm"><span>{compact(Number(person.vibemates))} VibeMates</span><span>{compact(Number(person.vibein_count))} VibeIn</span><span>{compact(Number(person.total_likes))} likes</span><span>{compact(Number(person.total_comments))} comments</span><span>{compact(Number(person.total_shares))} shares</span></div>{person.id!==user.id&&<Button variant="outline" size="sm" className="mt-3" onClick={async()=>{const {error:e}=person.vibed_in?await client.from('vibein').delete().eq('creator_id',person.id).eq('follower_id',user.id):await client.from('vibein').insert({creator_id:person.id,follower_id:user.id});if(e)toast.error(e.message);else setPerson({...person,vibed_in:!person.vibed_in,vibemates:Number(person.vibemates)+(person.vibed_in?-1:1)})}}>{person.vibed_in?'Remove VibeIn':'VibeIn'}</Button>}</div>}{loading?<p className="text-center py-12 text-muted-foreground">Loading VibZ…</p>:posts.length?<div className="space-y-4 snap-y snap-mandatory overflow-y-auto max-h-[77dvh] overscroll-contain">{posts.map(post=><VideoCard key={post.id} post={post} onCreator={id=>setSelected(id)} onUpdate={refresh}/>)}</div>:!error&&<div className="py-16 text-center"><Clapperboard className="mx-auto mb-3 text-primary" size={36}/><p className="font-semibold">No VibZ here yet</p><p className="text-sm text-muted-foreground">{selected?'This creator has not posted any VibZ.':'Create the first VibZ or discover creators.'}</p><Button variant="outline" className="mt-4" onClick={()=>setChooseOpen(true)}><Plus/>Create VibZ</Button></div>}</>}
  </div>
}
